[toolchain]

[features]
resolution = true
skip-lint = false

[programs.mainnet]
token_vesting = "DV4EuDaqC6oBKeAxm6fMvbdLR3JBd4NH44DASX6qozqu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["program"]
