export const NETWORK_CONNECTION_ENDPOINT =
  process.env.NEXT_PUBLIC_NETWORK_CONNECTION_ENDPOINT || "";
export const TOKEN_VESTING_PROGRAM_ID =
  process.env.NEXT_PUBLIC_TOKEN_VESTING_PROGRAM_ID || "";
